name: Prepare

description: Prepares the repo for a typical CI job

runs:
  using: composite
  steps:
    - name: Configure Git
      uses: ./.github/actions/git-config

    - name: ♻️ Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: 📥 Monorepo install
      uses: ./.github/actions/yarn-nm-install
