name: Prepare

description: Prepares the repo for a typical CI job

runs:
  using: composite
  steps:
    - uses: ./.github/actions/git-config

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
