name: Prepare

description: Prepares the repo for a typical CI job

inputs:
  node-version:
    required: false
    description: "`node-version` passed to `actions/setup-node`."
    default: latest

runs:
  using: composite
  steps:
    - uses: ./.github/actions/git-config

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
